"""
# Django settings for core project.
# Trigger Auto Deploy!

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import ssl
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'), override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (production-safe). Local development must opt in
# explicitly via DEBUG=True in a local .env (gitignored, never committed) --
# this previously defaulted to True, so a production boot that was ever
# missing this env var would silently run with verbose debug error pages
# and every other permissive fallback below.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# Production MUST set SECRET_KEY -- no fallback is available outside of
# local development (DEBUG=True), where an obviously-fake placeholder is
# used instead of a real-looking hardcoded key sitting in source control.
if DEBUG:
    SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-local-dev-only-do-not-use-in-production')
else:
    SECRET_KEY = os.environ.get('SECRET_KEY')
    if not SECRET_KEY:
        raise ImproperlyConfigured("SECRET_KEY environment variable must be set in production.")

# OpenAI API Key for Whisper Transcription
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# ALLOWED_HOSTS: production must set this explicitly. No '*' fallback --
# that would silently accept any Host header if the env var were ever
# missing from the deployment environment.
if DEBUG:
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
else:
    _allowed_hosts_env = os.environ.get('ALLOWED_HOSTS')
    if not _allowed_hosts_env:
        raise ImproperlyConfigured("ALLOWED_HOSTS environment variable must be set in production.")
    ALLOWED_HOSTS = _allowed_hosts_env.split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'storages',
    
    # Local Apps
    'users',
    'courses',
    'orders',
    'cms',
    'notifications',
    
    # Auth
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth.registration',
]

SITE_ID = 1

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    )
}

REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'natya-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'natya-refresh',
    'USER_DETAILS_SERIALIZER': 'users.serializers.CustomUserDetailsSerializer',
    'JWT_AUTH_SAMESITE': 'None',
    'JWT_AUTH_SECURE': True,
}

# Allow cookies to be sent cross-domain (Frontend -> Backend API)
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True

# Allow academy.natyaarts.com to read cookies set by api.natyaarts.com.
# Only applies in production: a cookie's Domain attribute must be the exact
# request host or a parent of it, so setting '.natyaarts.com' while running
# locally (localhost/127.0.0.1) makes browsers silently reject the cookie
# entirely -- the request "succeeds" but the user never actually gets logged
# in. COOKIE_DOMAIN defaults to None (no Domain attribute -> exact host,
# works everywhere including localhost) unless DEBUG is off, in which case
# it falls back to the production domain automatically. Override with the
# COOKIE_DOMAIN env var for other environments (e.g. staging).
COOKIE_DOMAIN = os.environ.get('COOKIE_DOMAIN', None if DEBUG else '.natyaarts.com')
CSRF_COOKIE_DOMAIN = COOKIE_DOMAIN
SESSION_COOKIE_DOMAIN = COOKIE_DOMAIN

# Tell Django it's behind a secure proxy so it sends Secure cookies over HTTP from the load balancer
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_LOGIN_ON_GET = True

# Post-social-login redirect target. Must never resolve to localhost in
# production regardless of whether FRONTEND_URL is explicitly set.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000' if DEBUG else 'https://academy.natyaarts.com')
LOGIN_REDIRECT_URL = f'{FRONTEND_URL}/dashboard'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# CORS/CSRF origins are environment-driven. Defaults keep localhost support
# for local development ONLY (DEBUG=True); the production defaults are the
# real deployed origins so this can't break live CORS/CSRF if the env vars
# aren't set yet in the deployment environment -- override via
# CORS_ALLOWED_ORIGINS / CSRF_TRUSTED_ORIGINS (comma-separated) to add more.
_default_cors_origins = (
    'http://localhost:3000,http://localhost:8081,http://localhost:8082,http://127.0.0.1:8081,http://127.0.0.1:8082'
    if DEBUG else
    'https://natya-lms.vercel.app,https://academy.natyaarts.com'
)
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', _default_cors_origins).split(',')
CORS_ALLOW_CREDENTIALS = True

_default_csrf_origins = (
    'http://localhost:3000,http://localhost:8081,http://localhost:8082'
    if DEBUG else
    'https://natya-lms.vercel.app,https://academy.natyaarts.com'
)
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', _default_csrf_origins).split(',')

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url
import os

# If AWS RDS is linked to Elastic Beanstalk, it provides these variables:
if 'RDS_DB_NAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
else:
    # Fallback to DATABASE_URL or SQLite for local development
    DATABASES = {
        'default': dj_database_url.config(
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
            conn_max_age=600,
            conn_health_checks=True,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# AWS S3 Configuration
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', '')
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
elif not DEBUG:
    raise ImproperlyConfigured(
        "AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME must all be set in "
        "production -- refusing to silently fall back to local/ephemeral disk storage for media uploads."
    )
# else: DEBUG and no S3 creds -- falls through to Django's default local
# FileSystemStorage (MEDIA_ROOT above), matching existing local dev behavior.

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

# Interakt WhatsApp API
# Production MUST set INTERAKT_SECRET_KEY -- no fallback outside local dev.
# (The previous fallback here was a real-looking, source-visible credential,
# not a placeholder -- rotate this key if it was ever live.)
if DEBUG:
    INTERAKT_SECRET_KEY = os.getenv('INTERAKT_SECRET_KEY', '')
else:
    INTERAKT_SECRET_KEY = os.getenv('INTERAKT_SECRET_KEY')
    if not INTERAKT_SECRET_KEY:
        raise ImproperlyConfigured("INTERAKT_SECRET_KEY environment variable must be set in production.")
INTERAKT_TEMPLATE_NAME = os.getenv('INTERAKT_TEMPLATE_NAME', 'login_otp_v1')

# Razorpay Settings
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '')

# Phase 3.2: a separate secret from RAZORPAY_KEY_SECRET, configured in the
# Razorpay dashboard specifically for webhook signature verification --
# never the same value as the API key secret.
#
# Deliberately NOT a hard fail-at-boot requirement (unlike SECRET_KEY/
# ALLOWED_HOSTS/S3/Celery in the earlier production-hardening pass): those
# were all pieces of already-running production infrastructure, so failing
# loudly at startup if one went missing was the safe choice. The webhook
# endpoint is brand new -- nothing in the current production environment
# has this variable set yet, and this app boots and serves checkout/login/
# every other route whether or not a webhook secret is configured. Crashing
# the ENTIRE application at startup over one new, optional-until-you-wire-
# it-up-in-the-Razorpay-dashboard feature would be strictly worse than the
# webhook endpoint alone refusing requests. RazorpayWebhookView checks this
# itself at request time and returns 400 (logged) if it's blank, so the
# feature degrades in isolation instead of taking the whole site down.
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET', '')

# Celery Configuration
# Production must set both env vars explicitly -- no localhost:6379
# fallback, which would silently point at a Redis that doesn't exist on
# the production host instead of failing at boot.
if DEBUG:
    CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
    CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
else:
    CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL')
    CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND')
    if not CELERY_BROKER_URL or not CELERY_RESULT_BACKEND:
        raise ImproperlyConfigured(
            "CELERY_BROKER_URL and CELERY_RESULT_BACKEND environment variables must be set in "
            "production -- refusing to silently fall back to a local Redis that doesn't exist on the server."
        )

if CELERY_BROKER_URL.startswith('rediss://'):
    CELERY_BROKER_USE_SSL = {'ssl_cert_reqs': ssl.CERT_REQUIRED}

if CELERY_RESULT_BACKEND.startswith('rediss://'):
    CELERY_REDIS_BACKEND_USE_SSL = {'ssl_cert_reqs': ssl.CERT_REQUIRED}

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# AI Translation Credentials
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY', '')