# Generated by Django 5.2.15 on 2026-08-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('COURSE_UPDATE', 'Course Update'), ('ENROLLMENT', 'Enrollment'), ('PAYMENT', 'Payment'), ('ANNOUNCEMENT', 'Announcement'), ('COURSE_COMPLETION', 'Course Completion'), ('CERTIFICATE', 'Certificate'), ('LIVE_CLASS', 'Live Class')], default='ANNOUNCEMENT', max_length=50),
        ),
    ]
