# Generated by Django 5.2.16 on 2026-09-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('COURSE_UPDATE', 'Course Update'), ('ENROLLMENT', 'Enrollment'), ('PAYMENT', 'Payment'), ('ANNOUNCEMENT', 'Announcement'), ('COURSE_COMPLETION', 'Course Completion'), ('CERTIFICATE', 'Certificate'), ('LIVE_CLASS', 'Live Class'), ('ASSIGNMENT', 'Assignment')], default='ANNOUNCEMENT', max_length=50),
        ),
    ]
