# Generated by Django 5.2.16 on 2026-09-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_subscriptionplan_subscription_subscriptionpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='razorpay_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
