# Generated by Django 5.2.16 on 2026-10-08 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0027_attendance_duration_minutes_attendance_joined_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('MONTHLY', 'Monthly'), ('EVERY_2_MONTHS', 'Every 2 Months'), ('EVERY_3_MONTHS', 'Every 3 Months'), ('EVERY_6_MONTHS', 'Every 6 Months'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('billing_interval_value', models.PositiveIntegerField(blank=True, help_text='Interval count for CUSTOM billing (e.g. 45).', null=True)),
                ('billing_interval_unit', models.CharField(blank=True, choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months'), ('YEARS', 'Years')], help_text='Interval unit for CUSTOM billing (e.g. DAYS).', max_length=20, null=True)),
                ('start_date', models.DateField(help_text='Configured initial effective start date anchoring all billing periods.')),
                ('current_period_start', models.DateField(help_text='Start date of current fee coverage period.')),
                ('current_period_end', models.DateField(help_text='End date of current fee coverage period.')),
                ('next_billing_date', models.DateField(blank=True, help_text='Anchor start date of next billing cycle. None for ONE_TIME.', null=True)),
                ('due_date', models.DateField(help_text='Target payment due date.')),
                ('advance_invoice_days', models.PositiveIntegerField(default=7, help_text='Days prior to next_billing_date when upcoming invoice is generated.')),
                ('grace_period_days', models.PositiveIntegerField(default=7, help_text='Grace days granted after due_date before content access is restricted.')),
                ('grace_until', models.DateField(blank=True, help_text='due_date + grace_period_days.', null=True)),
                ('access_restriction_date', models.DateField(blank=True, help_text='Canonical date content locks if unpaid (grace_until + 1 day).', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UPCOMING', 'Upcoming'), ('DUE', 'Due'), ('GRACE_PERIOD', 'Grace Period'), ('OVERDUE', 'Overdue'), ('RESTRICTED', 'Restricted'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='ACTIVE', max_length=30)),
                ('auto_generate_invoice', models.BooleanField(default=True, help_text='Automatically generate upcoming invoices via Celery schedule.')),
                ('auto_restrict_access', models.BooleanField(default=True, help_text='Automatically restrict course content access after grace_until.')),
                ('auto_send_reminders', models.BooleanField(default=True, help_text='Automatically send payment and grace period notifications.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='True if this is the active billing arrangement for this student+course.')),
                ('pending_billing_type', models.CharField(blank=True, choices=[('ONE_TIME', 'One Time'), ('MONTHLY', 'Monthly'), ('EVERY_2_MONTHS', 'Every 2 Months'), ('EVERY_3_MONTHS', 'Every 3 Months'), ('EVERY_6_MONTHS', 'Every 6 Months'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], help_text='Scheduled new billing type taking effect on next_billing_date.', max_length=30, null=True)),
                ('pending_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Scheduled new amount taking effect on next_billing_date.', max_digits=10, null=True)),
                ('pending_effective_date', models.DateField(blank=True, help_text='Target date when pending plan change activates.', null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_billing_plans', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_plans', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, help_text='Optional link to course enrollment. Enrollment is retained even if billing is overdue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_plans', to='courses.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Billing Plan',
                'verbose_name_plural': 'Student Billing Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingPlanChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_mode', models.CharField(choices=[('NEXT_CYCLE', 'Next Cycle (Standard)'), ('IMMEDIATE', 'Immediate')], max_length=30)),
                ('old_billing_type', models.CharField(max_length=30)),
                ('new_billing_type', models.CharField(max_length=30)),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(help_text='Anchor date when new plan terms take effect.')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_changes_made', to=settings.AUTH_USER_MODEL)),
                ('billing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='billing.studentbillingplan')),
            ],
            options={
                'verbose_name': 'Billing Plan Change Log',
                'verbose_name_plural': 'Billing Plan Change Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingAccessExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_status', models.CharField(help_text='Status of plan at time of override (e.g. OVERDUE, RESTRICTED).', max_length=30)),
                ('extended_until', models.DateField(help_text='Access guaranteed through this date regardless of invoice state.')),
                ('reason', models.TextField(help_text='Mandatory admin justification for audit compliance.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_access_extensions', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_extensions_granted', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_access_extensions', to=settings.AUTH_USER_MODEL)),
                ('billing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_extensions', to='billing.studentbillingplan')),
            ],
            options={
                'verbose_name': 'Billing Access Extension',
                'verbose_name_plural': 'Billing Access Extensions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('period_start', models.DateField(help_text='Start date of fee coverage period.')),
                ('period_end', models.DateField(help_text='End date of fee coverage period.')),
                ('issue_date', models.DateField(help_text='Date invoice was issued.')),
                ('due_date', models.DateField(help_text='Payment deadline.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('WAIVED', 'Waived')], db_index=True, default='ISSUED', max_length=30)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Method used when payment completed (RAZORPAY, CASH, UPI, etc.).', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.studentbillingplan')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Invoice',
                'verbose_name_plural': 'Student Invoices',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('WAIVED', 'Waived'), ('OTHER', 'Other')], default='CASH', max_length=50)),
                ('payment_date', models.DateTimeField()),
                ('reference_number', models.CharField(blank=True, help_text='Bank UTR, UPI transaction ID, cheque number, or offline receipt ID.', max_length=255)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='billing/receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_manual_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_payments', to='billing.studentinvoice')),
            ],
            options={
                'verbose_name': 'Manual Payment Record',
                'verbose_name_plural': 'Manual Payment Records',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentbillingplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'course'), name='unique_active_billing_plan_per_student_course'),
        ),
        migrations.AddConstraint(
            model_name='studentbillingplan',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='billing_plan_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentbillingplan',
            constraint=models.CheckConstraint(condition=models.Q(('current_period_start__lte', models.F('current_period_end'))), name='billing_plan_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='billingaccessextension',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'course'), name='unique_active_access_extension_per_student_course'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('billing_plan', 'period_start', 'period_end'), name='unique_invoice_per_billing_period'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='student_invoice_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='manualpaymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='manual_payment_amount_positive'),
        ),
    ]
