# Generated by Django 5.2.16 on 2026-10-08 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('UPCOMING', 'Upcoming Payment'), ('DUE_TODAY', 'Payment Due Today'), ('GRACE_STARTED', 'Grace Period Started'), ('GRACE_FINAL_WARNING', 'Grace Period Final Warning'), ('ACCESS_RESTRICTED', 'Access Restricted'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('ACCESS_RESTORED', 'Access Restored')], db_index=True, max_length=50)),
                ('period_start', models.DateField(help_text='Start date of fee coverage period this notification is for.')),
                ('scheduled_date', models.DateField(help_text='Date when this notification was eligible/scheduled.')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='SENT', max_length=20)),
                ('channel', models.CharField(default='ALL', help_text='Channels attempted (e.g. IN_APP, EMAIL, WHATSAPP, ALL)', max_length=50)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key: billing_notif:{plan_id}:{type}:{period_start}:{scheduled_date}', max_length=255, unique=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='billing.studentbillingplan')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='billing.studentinvoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Notification Log',
                'verbose_name_plural': 'Billing Notification Logs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('billing_plan', 'notification_type', 'period_start', 'scheduled_date'), name='unique_billing_reminder_per_cycle_event')],
            },
        ),
    ]
