# Generated by Django 5.2.16 on 2026-09-09 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0017_courseinstructor_commission_rate'),
        ('orders', '0006_subscriptionplan_razorpay_plan_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('method', models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('OTHER', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Bank transfer UTR or similar, once a payout is actually processed.', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('EARNING', 'Earning'), ('CLAWBACK', 'Clawback'), ('ADJUSTMENT', 'Adjustment')], default='EARNING', max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_instructor', models.ForeignKey(help_text='Who this entry attributes revenue to. PROTECT: financial history must survive a CourseInstructor row ever being removed.', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='courses.courseinstructor')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.orderitem')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.purchase')),
                ('related_entry', models.ForeignKey(blank=True, help_text='What a CLAWBACK/ADJUSTMENT entry corrects. Unused by any code in this phase.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='finance.ledgerentry')),
                ('subscription_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.subscriptionpayment')),
                ('payout', models.ForeignKey(blank=True, help_text='Null = not yet batched into a payout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.payout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['recipient', 'status'], name='finance_pay_recipie_a7cfb9_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['course_instructor', 'payout'], name='finance_led_course__dcdf9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order_item__isnull', True), ('purchase__isnull', False), ('subscription_payment__isnull', True)), models.Q(('order_item__isnull', False), ('purchase__isnull', True), ('subscription_payment__isnull', True)), models.Q(('order_item__isnull', True), ('purchase__isnull', True), ('subscription_payment__isnull', False)), _connector='OR'), name='ledgerentry_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('purchase__isnull', False)), fields=('purchase', 'entry_type'), name='ledgerentry_unique_purchase_entry_type'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('order_item__isnull', False)), fields=('order_item', 'entry_type'), name='ledgerentry_unique_orderitem_entry_type'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('subscription_payment__isnull', False)), fields=('subscription_payment', 'entry_type'), name='ledgerentry_unique_subscriptionpayment_entry_type'),
        ),
    ]
