# Generated by Django 5.2.16 on 2026-09-09 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0006_subscriptionplan_razorpay_plan_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_date', models.DateTimeField(help_text='When the underlying payment actually completed.')),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.purchase')),
                ('subscription_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.subscriptionpayment')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', True), ('purchase__isnull', False), ('subscription_payment__isnull', True)), models.Q(('order__isnull', False), ('purchase__isnull', True), ('subscription_payment__isnull', True)), models.Q(('order__isnull', True), ('purchase__isnull', True), ('subscription_payment__isnull', False)), _connector='OR'), name='invoice_exactly_one_source'), models.UniqueConstraint(condition=models.Q(('purchase__isnull', False)), fields=('purchase',), name='invoice_unique_purchase'), models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order',), name='invoice_unique_order'), models.UniqueConstraint(condition=models.Q(('subscription_payment__isnull', False)), fields=('subscription_payment',), name='invoice_unique_subscription_payment')],
            },
        ),
    ]
