# Generated by Django 5.2.16 on 2026-09-09 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_courseinstructor_commission_rate'),
        ('finance', '0002_invoice'),
        ('orders', '0007_alter_purchase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], db_index=True, default='REQUESTED', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='ledgerentry_unique_purchase_entry_type',
        ),
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='ledgerentry_unique_orderitem_entry_type',
        ),
        migrations.RemoveConstraint(
            model_name='ledgerentry',
            name='ledgerentry_unique_subscriptionpayment_entry_type',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='related_entry',
            field=models.ForeignKey(blank=True, help_text='What a CLAWBACK/ADJUSTMENT entry corrects. Set on every CLAWBACK entry (Phase 3.5.6); still unused for ADJUSTMENT, which no code creates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='finance.ledgerentry'),
        ),
        migrations.AddField(
            model_name='refund',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='orders.order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='orders.purchase'),
        ),
        migrations.AddField(
            model_name='refund',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='subscription_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='orders.subscriptionpayment'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clawback_entries', to='finance.refund'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'EARNING'), ('purchase__isnull', False)), fields=('purchase', 'entry_type'), name='ledgerentry_unique_purchase_entry_type'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'EARNING'), ('order_item__isnull', False)), fields=('order_item', 'entry_type'), name='ledgerentry_unique_orderitem_entry_type'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'EARNING'), ('subscription_payment__isnull', False)), fields=('subscription_payment', 'entry_type'), name='ledgerentry_unique_subscriptionpayment_entry_type'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('refund__isnull', False)), fields=('refund', 'related_entry'), name='ledgerentry_unique_refund_related_entry'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['customer', 'status'], name='finance_ref_custome_c9f78e_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', True), ('purchase__isnull', False), ('subscription_payment__isnull', True)), models.Q(('order__isnull', False), ('purchase__isnull', True), ('subscription_payment__isnull', True)), models.Q(('order__isnull', True), ('purchase__isnull', True), ('subscription_payment__isnull', False)), _connector='OR'), name='refund_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
    ]
