# Generated by Django 5.2.16 on 2026-07-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videolesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload the original MP4 video file', null=True, upload_to='videos/lessons/'),
        ),
    ]
