# Generated by Django 5.2.16 on 2026-07-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_videolesson_video_url_videolesson_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolesson',
            name='audio_hi_url',
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='audio_ml_url',
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='audio_ta_url',
        ),
        migrations.CreateModel(
            name='TranslatedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text='e.g. ml-IN, ta-IN, hi-IN, es-ES', max_length=10)),
                ('audio_file', models.FileField(upload_to='videos/audios/')),
                ('status', models.CharField(default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_audios', to='courses.videolesson')),
            ],
            options={
                'unique_together': {('lesson', 'language_code')},
            },
        ),
    ]
