# Generated by Django 5.2.16 on 2026-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_videolesson_audio_hi_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='transcript',
            field=models.TextField(blank=True, help_text='Paste the English transcript here. AI will use this to generate dubbed audio tracks.'),
        ),
    ]
