# Generated by Django 5.2.16 on 2026-08-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_videolesson_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='timed_transcript',
            field=models.TextField(blank=True, help_text='Manually timed transcript for perfect dubbing sync. Each line: HH:MM:SS --> Text spoken at that time. Example: 00:00:05 --> Hello and welcome to this class'),
        ),
    ]
