# Generated by Django 5.2.15 on 2026-08-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_liveclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('ONE_TO_ONE', 'One-to-One'), ('GROUP', 'Group'), ('RECORDED', 'Recorded')], db_index=True, default='RECORDED', max_length=20),
        ),
    ]
