# Generated by Django 5.2.15 on 2026-08-14 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_course_types_and_live_classes(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    LiveClass = apps.get_model('courses', 'LiveClass')
    LiveBatch = apps.get_model('courses', 'LiveBatch')

    # Precompute referenced courses to avoid N+1 queries
    courses_with_live_classes = set(
        LiveClass.objects.values_list('course_id', flat=True)
    )

    for course in Course.objects.all():
        if course.course_type in ['ONE_TO_ONE', 'GROUP']:
            course.course_type = 'LIVE'
            course.save()
        elif course.id in courses_with_live_classes:
            course.course_type = 'LIVE'
            course.save()

    for live_class in LiveClass.objects.all():
        if live_class.batch_id is None:
            # Reuses matching batch if exists, otherwise creates one (idempotent)
            batch, created = LiveBatch.objects.get_or_create(
                course=live_class.course,
                instructor=live_class.instructor,
                batch_type='GROUP'
            )
            live_class.batch = batch
            live_class.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_course_type'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('ONE_TO_ONE', 'One-to-One'), ('GROUP', 'Group')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_batches', to='courses.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_live_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Live Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveBatchStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.livebatch')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_batch_assignments', to='orders.purchase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_batch_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Live Batch Students',
                'ordering': ['-created_at'],
                'unique_together': {('batch', 'student')},
            },
        ),
        migrations.AddField(
            model_name='liveclass',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_classes', to='courses.livebatch'),
        ),
        migrations.RunPython(migrate_course_types_and_live_classes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('LIVE', 'Live'), ('RECORDED', 'Recorded')], db_index=True, default='RECORDED', max_length=20),
        ),
    ]
