# Generated by Django 5.2.16 on 2026-09-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_course_type_livebatch_liveclass_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedaudio',
            name='language_name',
            field=models.CharField(blank=True, default='', help_text="Display name, e.g. 'Malayalam'", max_length=100),
        ),
        migrations.AddField(
            model_name='translatedaudio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
