# Generated by Django 5.2.16 on 2026-09-02 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_translatedaudio_language_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TEACHER', 'Teacher'), ('MENTOR', 'Mentor'), ('ASSISTANT', 'Assistant')], default='TEACHER', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary instructor for revenue/payout attribution (future use).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructor_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
                'unique_together': {('course', 'user', 'role')},
            },
        ),
    ]
