# Generated by Django 5.2.16 on 2026-09-02 10:57

from django.db import migrations


def backfill_course_instructors(apps, schema_editor):
    """
    Phase 0: capture today's real teacher/course relationships into the new
    CourseInstructor table, derived from the existing (legacy) signal --
    a teacher having an Enrollment row in their own course. This is purely
    additive: no Enrollment row is touched, read, or removed by anything
    other than a plain SELECT here.
    """
    Enrollment = apps.get_model('courses', 'Enrollment')
    CourseInstructor = apps.get_model('courses', 'CourseInstructor')

    teacher_enrollments = Enrollment.objects.filter(
        user__is_teacher=True
    ).select_related('user', 'course')

    seen = set()
    for enrollment in teacher_enrollments:
        key = (enrollment.course_id, enrollment.user_id)
        if key in seen:
            continue
        seen.add(key)
        CourseInstructor.objects.get_or_create(
            course_id=enrollment.course_id,
            user_id=enrollment.user_id,
            role='TEACHER',
            defaults={'is_primary': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_courseinstructor'),
    ]

    operations = [
        # Reverse is a no-op (not a delete of all matching rows) -- once real
        # usage may have added further CourseInstructor rows, we can no
        # longer safely distinguish "backfilled by this migration" from
        # "created afterwards", so reversing this migration intentionally
        # leaves the data as-is rather than guessing what to remove.
        migrations.RunPython(backfill_course_instructors, reverse_code=migrations.RunPython.noop),
    ]
