# Generated by Django 5.2.16 on 2026-09-02 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_backfill_course_instructors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livebatch',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Only meaningful for GROUP batches. Leave blank for no cap. ONE_TO_ONE is always capped at 1 regardless of this field.', null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recording_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recording_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One-time'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='ONE_TIME', max_length=20)),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='For WEEKLY frequency: list of weekday ints, Monday=0..Sunday=6 (Python weekday()). Ignored otherwise.')),
                ('end_date', models.DateField(blank=True, help_text='Last date an occurrence may fall on. Mutually exclusive with occurrence_count in practice, but either/both may be set as a safety bound.', null=True)),
                ('occurrence_count', models.PositiveIntegerField(blank=True, help_text='Max number of occurrences to generate.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurrence_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, help_text='Set when this class was generated as part of a recurring series.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='courses.recurrencerule'),
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teacher Availability Windows',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='ABSENT', max_length=20)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.liveclass')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-marked_at'],
                'unique_together': {('live_class', 'student')},
            },
        ),
    ]
