# Generated by Django 5.2.16 on 2026-09-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstructor',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
