# Generated by Django 5.2.16 on 2026-09-12 05:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_courseinstructor_commission_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Shown to the student before they start the attempt.')),
                ('order', models.PositiveIntegerField(default=0, help_text="Display order among this module's assessments.")),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Minimum percentage of marks required to pass this assessment.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='How many times a student may attempt this assessment.', validators=[django.core.validators.MinValueValidator(1)])),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Leave blank for no time limit.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice')], default='SINGLE_CHOICE', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('marks', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Marks awarded for answering this question correctly. Decimal, not float, to keep scoring exact.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('explanation', models.TextField(blank=True, help_text='Optional explanation shown to the student after the attempt is graded (a later phase).')),
                ('is_required', models.BooleanField(default=True, help_text='Whether the student must answer this question to submit the attempt.')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.assessment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_module_assessment_order'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('assessment', 'order'), name='unique_assessment_question_order'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_question_option_order'),
        ),
    ]
