# Generated by Django 5.2.16 on 2026-09-12 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_assessment_question_questionoption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_answers', to='courses.question')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_links', to='courses.assessmentanswer')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_links', to='courses.questionoption')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='selected_options',
            field=models.ManyToManyField(related_name='selected_in_answers', through='courses.AssessmentAnswerOption', to='courses.questionoption'),
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(help_text='1-based, deterministic per (student, assessment) -- see AssessmentViewSet.start for how this is assigned race-safely.')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('TIMED_OUT', 'Timed Out')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='The authoritative clock-start used for time_limit_minutes -- never trust a client-provided start time.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='courses.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.assessmentattempt'),
        ),
        migrations.AddConstraint(
            model_name='assessmentansweroption',
            constraint=models.UniqueConstraint(fields=('answer', 'option'), name='unique_answer_option'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(fields=('student', 'assessment', 'attempt_number'), name='unique_student_assessment_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('student', 'assessment'), name='unique_active_attempt_per_student_assessment'),
        ),
        migrations.AddConstraint(
            model_name='assessmentanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_answer'),
        ),
    ]
