# Generated by Django 5.2.16 on 2026-09-12 12:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_assessmentanswer_assessmentansweroption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='marks_awarded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
