# Generated by Django 5.2.16 on 2026-09-13 06:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_assessmentanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentanswer',
            name='marks_possible',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.CreateModel(
            name='AssessmentAnswerOptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('was_correct', models.BooleanField()),
                ('order', models.PositiveIntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_snapshots', to='courses.assessmentanswer')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_option_snapshots', to='courses.questionoption')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('answer', 'option'), name='unique_answer_option_snapshot')],
            },
        ),
    ]
