# Generated by Django 5.2.16 on 2026-09-13 17:52

import courses.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Instructions shown to the student before they submit.')),
                ('max_marks', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Maximum marks a graded submission can be awarded. Decimal, not float, matching Question.marks.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(help_text='1-based, deterministic per (student, assignment) -- see AssignmentSubmissionViewSet.submit for race-safe assignment.')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('RETURNED_FOR_REVISION', 'Returned for Revision')], db_index=True, default='SUBMITTED', max_length=25)),
                ('content', models.TextField(blank=True, help_text='Optional text submission.')),
                ('submitted_file', models.FileField(blank=True, help_text='Optional file submission.', null=True, upload_to='assignments/submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png', 'zip']), courses.validators.validate_submission_file_size])),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, help_text="Null until graded. Must not exceed the assignment's max_marks -- enforced in the grading service, not here (a plain field validator can't see the related Assignment's own max_marks).", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='courses.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignment_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_module_assignment_order'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('student', 'assignment', 'attempt_number'), name='unique_student_assignment_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SUBMITTED')), fields=('student', 'assignment'), name='unique_pending_submission_per_student_assignment'),
        ),
    ]
