# Generated by Django 5.2.16 on 2026-10-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_assignment_assignmentsubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certificate of Completion', max_length=255)),
                ('institute_name', models.CharField(default='Natya Arts Academy', max_length=255)),
                ('institute_tagline', models.CharField(blank=True, default='Center for Excellence in Classical Indian Arts & Bharatanatyam', max_length=255)),
                ('presentation_line', models.CharField(default='This is proudly presented to', max_length=255)),
                ('description_text', models.TextField(default='has successfully completed the comprehensive training, modules, and practical demonstration for')),
                ('theme', models.CharField(default='temple_gold', max_length=50)),
                ('border_style', models.CharField(default='ornate_gold', max_length=50)),
                ('signatory1_name', models.CharField(blank=True, default='Guru Smt. Priyadarshini Govind', max_length=255)),
                ('signatory1_title', models.CharField(blank=True, default='Artistic Director & Chief Mentor', max_length=255)),
                ('signatory1_signature', models.TextField(blank=True, default='')),
                ('signatory2_name', models.CharField(blank=True, default='Dr. K. S. Subramanian', max_length=255)),
                ('signatory2_title', models.CharField(blank=True, default='Dean of Academy & External Examiner', max_length=255)),
                ('signatory2_signature', models.TextField(blank=True, default='')),
                ('logo_url', models.TextField(blank=True, default='')),
                ('seal_text', models.CharField(blank=True, default='NATYA ARTS • VERIFIED CREDENTIAL • EXCELLENCE', max_length=150)),
                ('show_qr', models.BooleanField(default=True)),
                ('show_verification_id', models.BooleanField(default=True)),
                ('show_issue_date', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='courses.course')),
            ],
        ),
    ]
