# Generated by Django 5.2.16 on 2026-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_certificatetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='custom_gold_color',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='logo_size',
            field=models.CharField(blank=True, default='md', max_length=10),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='name_font_style',
            field=models.CharField(blank=True, default='great_vibes', max_length=50),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='seal_type',
            field=models.CharField(blank=True, default='gold_medallion', max_length=50),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='seal_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='secondary_logo_size',
            field=models.CharField(blank=True, default='sm', max_length=10),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='secondary_logo_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signatory1_font',
            field=models.CharField(blank=True, default='Great Vibes', max_length=50),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signatory2_font',
            field=models.CharField(blank=True, default='Alex Brush', max_length=50),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='title_font_size',
            field=models.CharField(blank=True, default='lg', max_length=10),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='watermark_opacity',
            field=models.FloatField(blank=True, default=0.04),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='watermark_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
