# Generated by Django 5.2.16 on 2026-10-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_certificatetemplate_custom_gold_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='host_url',
            field=models.TextField(blank=True, default='', help_text='Host start_url with ZAK token for instructor/admin to launch meeting as host.'),
        ),
    ]
