# Generated by Django 5.2.16 on 2026-10-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_liveclass_host_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total minutes the student was present in this session'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='joined_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when student joined the session', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='left_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when student left the session', null=True),
        ),
    ]
