# Generated by Django 5.2.16 on 2026-07-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mastering Indian Classical Arts.', max_length=255)),
                ('subtitle', models.CharField(default='Welcome to Natya LMS', max_length=255)),
                ('description', models.TextField(default='Premium pre-recorded masterclasses, multi-lingual AI dubbing, and structured learning for all.')),
                ('button_text', models.CharField(default='Browse Masterclasses', max_length=100)),
                ('button_link', models.CharField(default='/courses', max_length=255)),
                ('bg_image_url', models.URLField(default='https://natyaarts.com/img/hero.png', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
