# Generated by Django 5.2.16 on 2026-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_parent_name_user_parent_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Variable name (e.g. dob, address). No spaces.', max_length=50)),
                ('label', models.CharField(help_text='Display label (e.g. Date of Birth)', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('date', 'Date Picker'), ('dropdown', 'Dropdown Select'), ('checkbox', 'Checkbox (True/False)')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, help_text='JSON list of options for dropdowns, e.g. ["Male", "Female"]', null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
