# Generated by Django 5.2.16 on 2026-09-02 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_mentor_mentorship'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/mentors/')),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('qualifications', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of language names, e.g. ["English", "Tamil"]')),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='e.g. {"instagram": "https://..."}')),
                ('is_public', models.BooleanField(default=True, help_text='Visible on a public mentor profile page (future use).')),
                ('is_active', models.BooleanField(default=True, help_text='Admin can deactivate the profile without touching the User account.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/teachers/')),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('qualifications', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of language names, e.g. ["English", "Malayalam"]')),
                ('short_intro', models.CharField(blank=True, max_length=500)),
                ('is_public', models.BooleanField(default=True, help_text='Visible on a public teacher profile page (future use).')),
                ('is_active', models.BooleanField(default=True, help_text='Admin can deactivate the profile without touching the User account.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
