# Generated by Django 5.2.16 on 2026-09-11 08:06

import django.core.validators
import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_mentorprofile_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/mentors/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), users.validators.validate_profile_image_size]),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/teachers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), users.validators.validate_profile_image_size]),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='Short machine-readable action code, e.g. ROLE_CHANGE, COURSE_INSTRUCTOR_ASSIGNED.', max_length=100)),
                ('target_type', models.CharField(blank=True, help_text="e.g. 'User', 'CourseInstructor', 'Refund', 'Payout'.", max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Non-sensitive structured detail only -- never a secret/credential/raw payment payload.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text="Who performed the action. Null only if the actor's account was later deleted.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='users_admin_target__1da144_idx')],
            },
        ),
    ]
