# Generated by Django 5.2.16 on 2026-09-23 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_otpverification_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('ACCOUNT_DELETION', 'Account Deletion')], db_index=True, default='LOGIN', max_length=30),
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional user-provided reason for deleting account.')),
                ('error_message', models.TextField(blank=True, help_text='Failure reason if status=FAILED.')),
                ('cleanup_log', models.JSONField(blank=True, default=dict, help_text='Structured audit log of staged cleanup actions (e.g., razorpay_cancelled, s3_files_deleted).')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Timestamp when deletion OTP was successfully verified.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when anonymization/cleanup completed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User requesting deletion.', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['COMPLETED', 'FAILED', 'CANCELLED']), _negated=True), fields=('user',), name='unique_active_deletion_request_per_user')],
            },
        ),
    ]
